import 'explanation.dart';

/// Suggestion generated by the intelligence engine
class Suggestion {
  final String id;
  final String title;
  final String description;
  final String actionType; // 'swap', 'reassign', 'day_off'
  final Explanation explanation;
  
  // Action details (simplified for now)
  final String? workerId;
  final int? dayIndex;
  final String? targetShiftId;
  final String? secondaryWorkerId; // For swaps

  Suggestion({
    required this.id,
    required this.title,
    required this.description,
    required this.actionType,
    required this.explanation,
    this.workerId,
    this.dayIndex,
    this.targetShiftId,
    this.secondaryWorkerId,
  });
}
